"""Agregar obligatoriedad de id_plan a Curso y Estudiante

Revision ID: 4d1c6f81bb44
Revises: f050ca0742d8
Create Date: 2026-07-10 00:32:43.903888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d1c6f81bb44'
down_revision = 'f050ca0742d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('curso', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_plan', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'plan_estudios', ['id_plan'], ['id_plan'])

    with op.batch_alter_table('estudiante', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_plan', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'plan_estudios', ['id_plan'], ['id_plan'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estudiante', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_plan')

    with op.batch_alter_table('curso', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_plan')

    # ### end Alembic commands ###
