"""add_capacidad_and_estado_to_seccion

Revision ID: b3bfae78c500
Revises: ab06815901e9
Create Date: 2026-07-12 11:47:36.643722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3bfae78c500'
down_revision = 'ab06815901e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seccion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('capacidad', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('estado', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seccion', schema=None) as batch_op:
        batch_op.drop_column('estado')
        batch_op.drop_column('capacidad')

    # ### end Alembic commands ###
