"""Agregar columna ciclo a estudiante

Revision ID: d46b6304ea31
Revises: b3bfae78c500
Create Date: 2026-07-13 03:32:22.171467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd46b6304ea31'
down_revision = 'b3bfae78c500'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estudiante', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ciclo', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estudiante', schema=None) as batch_op:
        batch_op.drop_column('ciclo')

    # ### end Alembic commands ###
