"""Fase 1: modelo inicial (18 tablas)

Revision ID: f050ca0742d8
Revises: 
Create Date: 2026-07-02 11:21:08.991938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f050ca0742d8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curso',
    sa.Column('id_curso', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('creditos', sa.Integer(), nullable=False),
    sa.Column('horas_teoria', sa.Integer(), nullable=False),
    sa.Column('horas_practica', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_curso'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('docente',
    sa.Column('id_docente', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('dni', sa.String(length=15), nullable=False),
    sa.Column('nombres', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=100), nullable=False),
    sa.Column('correo', sa.String(length=120), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.Column('condicion', sa.String(length=50), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('id_facultad', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_docente'),
    sa.UniqueConstraint('codigo'),
    sa.UniqueConstraint('dni')
    )
    op.create_table('facultad',
    sa.Column('id_facultad', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('id_decano', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_decano'], ['docente.id_docente'], ),
    sa.PrimaryKeyConstraint('id_facultad'),
    sa.UniqueConstraint('codigo')
    )
    # docente.id_facultad -> facultad.id_facultad se agrega aqui (no en el create_table
    # de 'docente') porque facultad.id_decano -> docente.id_docente crea un ciclo:
    # ambas tablas no pueden crearse con su FK cruzada de una sola vez.
    op.create_foreign_key(
        'fk_docente_facultad', 'docente', 'facultad', ['id_facultad'], ['id_facultad']
    )
    op.create_table('periodo_academico',
    sa.Column('id_periodo', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id_periodo')
    )
    op.create_table('rol',
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=30), nullable=False),
    sa.Column('descripcion', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id_rol'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('especialidad',
    sa.Column('id_especialidad', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('id_facultad', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_facultad'], ['facultad.id_facultad'], ),
    sa.PrimaryKeyConstraint('id_especialidad'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('estudiante',
    sa.Column('id_estudiante', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('dni', sa.String(length=15), nullable=False),
    sa.Column('nombres', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=100), nullable=False),
    sa.Column('correo', sa.String(length=120), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('id_especialidad', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_especialidad'], ['especialidad.id_especialidad'], ),
    sa.PrimaryKeyConstraint('id_estudiante'),
    sa.UniqueConstraint('codigo'),
    sa.UniqueConstraint('dni')
    )
    op.create_table('plan_estudios',
    sa.Column('id_plan', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('fecha_aprobacion', sa.Date(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('id_especialidad', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_especialidad'], ['especialidad.id_especialidad'], ),
    sa.PrimaryKeyConstraint('id_plan')
    )
    op.create_table('matricula',
    sa.Column('id_matricula', sa.Integer(), nullable=False),
    sa.Column('id_estudiante', sa.Integer(), nullable=False),
    sa.Column('id_periodo', sa.Integer(), nullable=False),
    sa.Column('fecha_matricula', sa.DateTime(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['id_estudiante'], ['estudiante.id_estudiante'], ),
    sa.ForeignKeyConstraint(['id_periodo'], ['periodo_academico.id_periodo'], ),
    sa.PrimaryKeyConstraint('id_matricula'),
    sa.UniqueConstraint('id_estudiante', 'id_periodo', name='uq_matricula_estudiante_periodo')
    )
    op.create_table('plan_curso',
    sa.Column('id_plan_curso', sa.Integer(), nullable=False),
    sa.Column('id_plan', sa.Integer(), nullable=False),
    sa.Column('id_curso', sa.Integer(), nullable=False),
    sa.Column('ciclo', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_curso'], ['curso.id_curso'], ),
    sa.ForeignKeyConstraint(['id_plan'], ['plan_estudios.id_plan'], ),
    sa.PrimaryKeyConstraint('id_plan_curso'),
    sa.UniqueConstraint('id_plan', 'id_curso', name='uq_plan_curso')
    )
    op.create_table('usuario',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('id_estudiante', sa.Integer(), nullable=True),
    sa.Column('id_docente', sa.Integer(), nullable=True),
    sa.Column('nombres', sa.String(length=100), nullable=True),
    sa.Column('apellidos', sa.String(length=100), nullable=True),
    sa.Column('correo', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['id_docente'], ['docente.id_docente'], ),
    sa.ForeignKeyConstraint(['id_estudiante'], ['estudiante.id_estudiante'], ),
    sa.ForeignKeyConstraint(['id_rol'], ['rol.id_rol'], ),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('id_docente'),
    sa.UniqueConstraint('id_estudiante'),
    sa.UniqueConstraint('username')
    )
    op.create_table('auditoria',
    sa.Column('id_auditoria', sa.Integer(), nullable=False),
    sa.Column('accion', sa.String(length=100), nullable=False),
    sa.Column('tabla', sa.String(length=50), nullable=False),
    sa.Column('registro', sa.String(length=50), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_auditoria')
    )
    op.create_table('documento',
    sa.Column('id_documento', sa.Integer(), nullable=False),
    sa.Column('tipo_documento', sa.String(length=50), nullable=False),
    sa.Column('fecha_solicitud', sa.DateTime(), nullable=False),
    sa.Column('fecha_emision', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('archivo', sa.String(length=255), nullable=True),
    sa.Column('codigo_qr', sa.String(length=255), nullable=True),
    sa.Column('id_estudiante', sa.Integer(), nullable=False),
    sa.Column('id_usuario_emite', sa.Integer(), nullable=True),
    sa.Column('id_usuario_autoriza', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_estudiante'], ['estudiante.id_estudiante'], ),
    sa.ForeignKeyConstraint(['id_usuario_autoriza'], ['usuario.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_usuario_emite'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_documento')
    )
    op.create_table('pago',
    sa.Column('id_pago', sa.Integer(), nullable=False),
    sa.Column('fecha_pago', sa.DateTime(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('metodo_pago', sa.String(length=30), nullable=True),
    sa.Column('codigo_operacion', sa.String(length=50), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('id_matricula', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_matricula'], ['matricula.id_matricula'], ),
    sa.PrimaryKeyConstraint('id_pago')
    )
    op.create_table('seccion',
    sa.Column('id_seccion', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=5), nullable=False),
    sa.Column('horario', sa.String(length=100), nullable=True),
    sa.Column('aula', sa.String(length=50), nullable=True),
    sa.Column('capacidad', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('id_plan_curso', sa.Integer(), nullable=False),
    sa.Column('id_docente', sa.Integer(), nullable=True),
    sa.Column('id_periodo', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_docente'], ['docente.id_docente'], ),
    sa.ForeignKeyConstraint(['id_periodo'], ['periodo_academico.id_periodo'], ),
    sa.ForeignKeyConstraint(['id_plan_curso'], ['plan_curso.id_plan_curso'], ),
    sa.PrimaryKeyConstraint('id_seccion')
    )
    op.create_table('matricula_detalle',
    sa.Column('id_matricula_detalle', sa.Integer(), nullable=False),
    sa.Column('id_matricula', sa.Integer(), nullable=False),
    sa.Column('id_seccion', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['id_matricula'], ['matricula.id_matricula'], ),
    sa.ForeignKeyConstraint(['id_seccion'], ['seccion.id_seccion'], ),
    sa.PrimaryKeyConstraint('id_matricula_detalle'),
    sa.UniqueConstraint('id_matricula', 'id_seccion', name='uq_matricula_seccion')
    )
    op.create_table('silabo',
    sa.Column('id_silabo', sa.Integer(), nullable=False),
    sa.Column('archivo', sa.String(length=255), nullable=False),
    sa.Column('fecha_subida', sa.DateTime(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('id_seccion', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_seccion'], ['seccion.id_seccion'], ),
    sa.PrimaryKeyConstraint('id_silabo'),
    sa.UniqueConstraint('id_seccion')
    )
    op.create_table('nota',
    sa.Column('id_nota', sa.Integer(), nullable=False),
    sa.Column('parcial1', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('parcial2', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('final', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('sustitutorio', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('promedio', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('id_matricula_detalle', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_matricula_detalle'], ['matricula_detalle.id_matricula_detalle'], ),
    sa.PrimaryKeyConstraint('id_nota'),
    sa.UniqueConstraint('id_matricula_detalle')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_docente_facultad', 'docente', type_='foreignkey')
    op.drop_table('nota')
    op.drop_table('silabo')
    op.drop_table('matricula_detalle')
    op.drop_table('seccion')
    op.drop_table('pago')
    op.drop_table('documento')
    op.drop_table('auditoria')
    op.drop_table('usuario')
    op.drop_table('plan_curso')
    op.drop_table('matricula')
    op.drop_table('plan_estudios')
    op.drop_table('estudiante')
    op.drop_table('especialidad')
    op.drop_table('rol')
    op.drop_table('periodo_academico')
    op.drop_table('facultad')
    op.drop_table('docente')
    op.drop_table('curso')
    # ### end Alembic commands ###
